---
driver:
  name: vagrant

provisioner:
  #name: chef_solo
  name: chef_zero
  data_path: test/shared

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[BBS-provision-cookbook-windows::default]
    attributes:
      bioc_version: "3.3"
      r_version: "3.3"
      use_r_devel: true
