name 'BBS-provision-cookbook'
maintainer 'Dan Tenenbaum'
maintainer_email 'dtenenba@fredhutch.org'
license 'Artistic 2.0'
description 'Installs Bioconductor System Dependencies'
long_description 'Installs Bioconductor System Dependencies'
version '0.1.0'
